"""Embed the checked numerical CSV data in a self-contained PGFPlots figure.

Run with the Python standard library only:
    python build_inline_figure.py
The generated fragment has no file dependencies at TeX compilation time.
"""
import csv
import hashlib
from pathlib import Path

root = Path(__file__).resolve().parent
data_file = root / "distortion_summary.csv"
with data_file.open(newline="", encoding="utf-8") as f:
    rows = list(csv.DictReader(f))
with (root / "closed_certificates.csv").open(newline="", encoding="utf-8") as f:
    certificates = {int(row["d"]): row for row in csv.DictReader(f)}

def coordinates(subset, field):
    # Preserve the source CSV decimal strings; do not round or refit data.
    return " ".join(f"({row['m']},{row[field]})" for row in subset)

limits = (0.8 * min(float(row["q10"]) for row in rows),
          1.25 * max(float(row["q90"]) for row in rows))
parts = [r"""% Generated by build_inline_figure.py from distortion_summary.csv.
% Source CSV SHA256: HASH
% Required preamble:
%   \usepackage{graphicx,tikz,pgfplots}
%   \usepgfplotslibrary{groupplots,fillbetween}
%   \pgfplotsset{compat=1.18}
% All data and certificate coordinates are embedded below.
% Exact certificate values are 33968 and 489430; neither was simulated.
\begin{figure}[t]
\centering
\begingroup
\definecolor{krBlue}{RGB}{36,94,166}
\definecolor{krOrange}{RGB}{182,83,32}
\resizebox{\linewidth}{!}{%
\begin{tikzpicture}
\begin{groupplot}[
 group style={group size=2 by 2,horizontal sep=0.8cm,vertical sep=1.35cm},
 width=7.1cm,height=4.5cm,scale only axis,
 xmode=log,ymode=log,log basis x=2,
 xmin=56,xmax=9400,
 xtick={64,256,1024,4096,8192},
 xticklabels={64,256,1024,4096,8192},
 ymin=YMIN,ymax=YMAX,
 xlabel={Sketch width $m$},
 ylabel={$\|U^\top\Omega\Omega^\top U-I_8\|_2$},
 tick label style={font=\small},
 label style={font=\small},title style={font=\small},
 grid=major,major grid style={gray!25,line width=0.3pt},
 minor tick num=0,
 legend style={font=\footnotesize,at={(0.985,0.985)},anchor=north east,
               draw=gray!35,fill=white,cells={anchor=west}},
]
""".replace("HASH", hashlib.sha256(data_file.read_bytes()).hexdigest())
       .replace("YMIN", format(limits[0], ".17g"))
       .replace("YMAX", format(limits[1], ".17g"))]

for d in (2, 3):
    title = rf"$d={d}$: $r=n=8$, $N={8**d}$"
    extra = ",ylabel={},yticklabels={}" if d == 3 else ""
    parts.append(rf"\nextgroupplot[title={{{title}}}{extra}]"+"\n")
    for geometry, color, marker, name in (("common_factor", "krOrange", "*", "Common factor"),
                                          ("haar", "krBlue", "square*", "Haar subspace")):
        subset = [row for row in rows if int(row["d"]) == d and row["geometry"] == geometry]
        path = f"d{d}{geometry}"
        parts.append(rf"\addplot[draw=none,name path={path}lo,forget plot] coordinates {{{coordinates(subset, 'q10')}}};"+"\n")
        parts.append(rf"\addplot[draw=none,name path={path}hi,forget plot] coordinates {{{coordinates(subset, 'q90')}}};"+"\n")
        parts.append(rf"\addplot[draw=none,fill={color},fill opacity=0.18,forget plot] fill between[of={path}lo and {path}hi];"+"\n")
        parts.append(rf"\addplot[color={color},line width=1.1pt,mark={marker},mark size=1.7pt] coordinates {{{coordinates(subset, 'median')}}};"+"\n")
        if d == 2:
            parts.append(rf"\addlegendentry{{{name}}}"+"\n")
    parts.append(r"\addplot[black!70,dashed,line width=0.8pt] coordinates {(56,0.5) (9400,0.5)};"+"\n")
    if d == 2:
        parts.append(r"\addlegendentry{$\varepsilon=0.5$}"+"\n")

for d in (2, 3):
    mc = certificates[d]["m_cert"]
    label = f"{int(mc):,}".replace(",", r"\,")
    parts.append(r"""\nextgroupplot[
 height=1.2cm,xmode=log,log basis x=10,ymode=normal,
 xmin=50,xmax=1000000,ymin=-1,ymax=1,
 xlabel={},ylabel={},ytick=\empty,
 xtick={100,10000,1000000},xticklabels={$10^2$,$10^4$,$10^6$},
 axis x line*=bottom,axis y line=none,grid=none,
 clip=false,
]
\addplot[black!45,line width=5pt,forget plot] coordinates {(64,0.45) (8192,0.45)};
\node[font=\footnotesize,anchor=north] at (axis cs:724.0773439350247,0.28) {Sampled widths};
""")
    parts.append(rf"\addplot[black,dashed,line width=0.8pt,forget plot] coordinates {{({mc},-1) ({mc},1)}};"+"\n")
    parts.append(rf"\node[font=\footnotesize,anchor=south east,fill=white,inner sep=1pt] at (axis cs:{mc},0.70) {{$m_{{\mathrm{{cert}}}}={label}$}};"+"\n")

parts.append(r"""\end{groupplot}
\end{tikzpicture}%
}
\endgroup
\caption{Median Gaussian tensor-sketch distortion and empirical
$10$th--$90$th percentile bands from $64$ trials.
Each order uses a fixed common-factor space
$\operatorname{span}\{e_a\otimes e_1\otimes\cdots\otimes e_1:1\le a\le8\}$
and one fixed Haar space of rank $8$. The dashed line is $\varepsilon=0.5$.
The lower logarithmic strips mark the sampled widths and the sufficient
closed-certificate widths $33\,968$ and $489\,430$; neither certificate
width was simulated. This fixed-rank illustration does not establish
the asymptotic dimension rate.}
\label{fig:kr-numerical-distortion}
\end{figure}
""")
out = root / "figure_inline.tex"
out.write_text("".join(parts), encoding="utf-8")
print(f"Wrote {out} ({out.stat().st_size} bytes)")
